version: "3"

services:
  hack_app:
    build: .
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=8080
    volumes:
      - './src:/hackapp/src'
      - './build:/hackapp/build'
      - './config:/hackapp/config'
      - './static:/hackapp/static'
      - './test:/hackapp/test'
